---
version: 2.1
jobs:
  build:
    docker:
      - image: isic/isic-challenge-scoring-test:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox
  release:
    docker:
      - image: isic/isic-challenge-scoring-test:latest
    steps:
      - checkout
      - run:
          name: Publish to PyPI
          command: tox -e release
workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:  # required since `release` has tag filters AND requires `build`
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
