name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          uv run tox
